version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@mdn/*"
    groups:
      deps:
        dependency-type: production
        exclude-patterns:
          - "@mdn/*"
      deps-dev:
        dependency-type: development
        exclude-patterns:
          - "@mdn/*"
      mdn:
        patterns:
          - "@mdn/*"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps): "
